# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - HATIME0azurepetstore

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://hatime0azurepetstorecr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_917e19d1db5a47639b5abf1fb0fa5de1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7f756e80bbce4ef390850f10dea5e7b7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: hatime0azurepetstorecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_917e19d1db5a47639b5abf1fb0fa5de1 }}/HATIME0azurepetstore:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HATIME0azurepetstore'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4d7db79d38c9492382d23d954980b149 }}
        images: 'hatime0azurepetstorecr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_917e19d1db5a47639b5abf1fb0fa5de1 }}/HATIME0azurepetstore:${{ github.sha }}'